name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: 'Node.js v24'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - uses: actions/checkout@v7
      - name: 'Cache node_modules'
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Run Tests
        run: npm test